spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 413730
    url: jdbc:mysql://127.0.0.1:3306/workbook?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      enabled: true
      location: D:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: e8435cddee04055cd1bade598c5fdf10
            client-secret: Ms3I3UjuwEdEIsERyipgSIzstRbjIBDt
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email

#logging:
#  level:
#    org.springframework: info
#    com.example: debug
#    org.springframework.security: trace

com.example.workbook.path: D:\\upload

springdoc:
  packages-to-scan: com.example.workbook.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html # default url: http:127.0.0.1:8080/swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true